### ISSUE TITLE
addon gets disabled from last Kodi 19, py3 support

### ISSUE THREAD

**Issue by Omikronpercy** [knaerzche/plugin.video.joyn#4]
Great addon, Thanks!

Version  0301 disables the addon. 
https://forum.kodi.tv/showthread.php?tid=343068&page=53

Thanks!

**Comment by knaerzche** [comment]
@Omikronpercy, thanks for letting me know. This is a change that was introduced by kodi maintainers 2 or 3 days ago. It wasn't announced anywhere (besides a forum thread). Its a small change for me, but I will have to wait until inputstreamhelper has an updated version, since my addon relies on this addon.

**Comment by Essam311** [comment]
@knaerzche inputstreamhelper is now on Kodi Matrix repo https://mirrors.kodi.tv/addons/matrix/script.module.inputstreamhelper/.

**Comment by knaerzche** [comment]
Matrix version can now be downloaded at https://github.com/knaerzche/plugin.video.joyn/releases/download/66fe1df/plugin.video.joyn-2.3.2.1-matrix.zip.
Thanks @Essam311 for letting me know about the inpustreamhelper matrix version.
