### ISSUE TITLE
Joyn Addon startet streams nicht. 

### ISSUE THREAD

**Issue by 3rr0rt1gg3r** [knaerzche/plugin.video.joyn#5]
Hallo,
Leider werden die streams nicht mehr gestartet. 
Hat sich wieder der Server geändert? Habe die letzte Version von dir installiert. Habe es auch schon deinstalliert und neu installiert. Keine änderung. Getestet auf coreelec (s905x2 / s905) und aftv mit kodi.

**Comment by knaerzche** [comment]
Hi,
I assume you're running kodi on linux? There was an update to widevine cdm recently and you might got the latest already, since inputstreamhelper checks for updates every 31 days per default. You can force that with inputstreamhelper settings -> (Re)install Widevine CDM library. After that reboot please.
If that doesn't solve your issue -> please upload a kodi debug log somewhere.

On Github: english only, please.

**Comment by knaerzche** [comment]
Pls open a new issue if the problem persists
